(function(){var f,k,l,g,i,a,h=function(a,c){return function(){return a.apply(c,arguments)}},p=Object.prototype.hasOwnProperty,j=function(a,c){function n(){this.constructor=a}for(var h in c)p.call(c,h)&&(a[h]=c[h]);n.prototype=c.prototype;a.prototype=new n;a.__super__=c.prototype;return a};i="undefined"!==typeof exports&&null!==exports?exports:this;g=i.NotebookJS=null!=(a=i.NotebookJS)?a:{};l=function(a){function c(){this.serialize=h(this.serialize,this);this.readyCells=h(this.readyCells,this);this.initialize=
h(this.initialize,this);this.defaults=h(this.defaults,this);c.__super__.constructor.apply(this,arguments)}j(c,a);c.prototype.defaults=function(){return{title:"untitled"}};c.prototype.initialize=function(){};c.prototype.readyCells=function(){this.cells=new k;return this.cells.localStorage=new Store("cells-"+this.get("id"))};c.prototype.serialize=function(){var a;a=this.toJSON();a.cells=this.cells.toJSON();return JSON.stringify(a)};return c}(Backbone.Model);i=function(a){function c(){c.__super__.constructor.apply(this,
arguments)}j(c,a);c.prototype.model=l;c.prototype.localStorage=new Store("notebook.js");return c}(Backbone.Collection);f=function(a){function c(){this.handleMessage=h(this.handleMessage,this);this.evaluateError=h(this.evaluateError,this);this.evaluateSuccess=h(this.evaluateSuccess,this);this.interrupt=h(this.interrupt,this);this.evaluate=h(this.evaluate,this);this.toggleInputFold=h(this.toggleInputFold,this);this.toggleType=h(this.toggleType,this);this.defaults=h(this.defaults,this);c.__super__.constructor.apply(this,
arguments)}j(c,a);c.prototype.tagName="li";c.prototype.defaults=function(){return{input:"",type:"javascript",inputFold:!1,output:null,position:null,error:null,state:null}};c.prototype.toggleType=function(){"javascript"===this.get("type")?this.set({type:"markdown"}):this.set({type:"javascript"});return this.set({state:"dirty"})};c.prototype.toggleInputFold=function(){this.set({inputFold:!this.get("inputFold")});return this.save()};c.prototype.evaluate=function(){this.set({output:null,error:null});
this.set({state:"evaluating"});this.save();this.handler=g.engines[this.get("type")];return this.handler.evaluate(this.get("input"),this)};c.prototype.interrupt=function(){if(null!=this.handler)return this.onPrint("Interrupted","error"),this.handler.interrupt(),this.set({state:null}),this.save()};c.prototype.evaluateSuccess=function(a){this.set({output:a,error:null});return this.save()};c.prototype.evaluateError=function(a){this.set({error:a});return this.save};c.prototype.handleMessage=function(a){switch(a.msg){case "evalEnd":return this.set({state:null}),
this.save();case "error":return this.onPrint(a.data,"error");case "print":return this.onPrint(a.data,"print");case "result":return this.onPrint(a.data,"print");case "raw":return this.onPrint(a.data,"raw")}};c.prototype.onError=function(a){return this.set({error:a})};c.prototype.onPrint=function(a,c){return this.set({output:(this.get("output")||"").concat('<div class="'+c+'">'+a+"</div>")})};return c}(Backbone.Model);k=function(a){function c(){this.comparator=h(this.comparator,this);c.__super__.constructor.apply(this,
arguments)}j(c,a);c.prototype.model=f;c.prototype.posJump=Math.pow(2,16);c.prototype.comparator=function(a,c){a=a.get("position");c=c.get("position");return a>c?1:a<c?-1:0};c.prototype.createAtEnd=function(){return this.create({position:this.length?this.at(this.length-1).get("position")+this.posJump:this.posJump})};c.prototype.createBefore=function(a){var c;c=this.indexOf(a);a=a.get("position");c=0===c?0:this.at(c-1).get("position");return this.create({position:(a+c)/2})};return c}(Backbone.Collection);
g.Notebook=l;g.Notebooks=i;g.Cell=f;g.Cells=k}).call(this);(function(){var f,k,l,g,i=function(a,h){return function(){return a.apply(h,arguments)}};k="undefined"!==typeof exports&&null!==exports?exports:this;k=k.NotebookJS=null!=(f=k.NotebookJS)?f:{};(function(){function a(){this.evaluate=i(this.evaluate,this)}a.prototype.evaluate=function(a,f){var j;try{if(j=eval(a),null!=j)return console.log("result",j),f.handleMessage({msg:"result",data:j.toString()})}catch(g){return console.log(g.message,g.stack),f.handleMessage({msg:"error",data:g.toString()})}finally{f.handleMessage({msg:"evalEnd"})}};
return a})();f=function(){function a(){this.evaluate=i(this.evaluate,this)}a.prototype.evaluate=function(a,f){var g,i;try{return i=new Showdown.converter,g=i.makeHtml(a),f.handleMessage({msg:"raw",data:g})}catch(c){return console.log(c.message),onErr(c.message)}finally{f.handleMessage({msg:"evalEnd"})}};return a}();l=function(){function a(){this.interrupt=i(this.interrupt,this);this.handleMessage=i(this.handleMessage,this);this.evaluate=i(this.evaluate,this);this.worker=new Worker("/src/worker.js");
this.worker.onmessage=this.handleMessage;this.inputId=0;this.handlers={}}a.prototype.evaluate=function(a,f){this.inputId+=1;this.handlers[this.inputId]=f;return this.worker.postMessage({src:a,id:this.inputId})};a.prototype.handleMessage=function(a){return this.handlers[a.data.inputId].handleMessage(a.data)};a.prototype.interrupt=function(){this.worker.terminate();this.worker=new Worker("/src/worker.js");return this.worker.onmessage=this.handleMessage};return a}();g={};g.javascript=new l;g.markdown=
new f;k.engines=g}).call(this);(function(){var f,k,l,g,i,a,h,p,j,o,c,n,r,q,t,d=function(a,b){return function(){return a.apply(b,arguments)}},u=Object.prototype.hasOwnProperty,m=function(a,b){function e(){this.constructor=a}for(var c in b)u.call(b,c)&&(a[c]=b[c]);e.prototype=b.prototype;a.prototype=new e;a.__super__=b.prototype;return a};_.templateSettings={interpolate:/\[\[=(.+?)\]\]/g,evaluate:/\[\[(.+?)\]\]/g};f="undefined"!==typeof exports&&null!==exports?exports:this;a=f.NotebookJS=null!=(t=f.NotebookJS)?t:{};j=function(a){var b,
e,c;e=$(window).scrollTop()+60;b=$(window).scrollTop()+$(window).height()-30;c=a.offset().top;return c+a.height()<=b&&c>=e};r=function(a){a=a.offset().top-90;console.log("stat",a);return $(window).scrollTop(a)};n=function(a){a=a.offset().top+a.height()+60-$(window).height();console.log("stab",a);return $("body").scrollTop(a)};f=function(a){function b(){this.generateToc=d(this.generateToc,this);this.typeset=d(this.typeset,this);this.share=d(this.share,this);this.saveToFile=d(this.saveToFile,this);
this.mathjaxReady=d(this.mathjaxReady,this);this.handleTocJump=d(this.handleTocJump,this);b.__super__.constructor.apply(this,arguments)}m(b,a);b.prototype.className="app";b.prototype.handleTocJump=function(e){window.e=e;if(e=$(e.target).attr("href"))return e=$("#"+e),r(e)};b.prototype.mathjaxReady=function(){return this.typeset()};b.prototype.saveToFile=function(e){var a;a=this.model.serialize();$(e.target).attr("download","notebook-"+(new Date).toISOString().slice(0,10)+".json");return $(e.target).attr("href",
"data:application/json;charset=utf-8,"+escape(a))};b.prototype.share=function(){var e,a;e=btoa(this.model.serialize());a=escape("http://notebookjs.me/#import/"+e+"/");e=_.template($("#share-notebook").html());console.log("template");console.log(a);return window.open("data:text/html;charset=utf-8,"+e({url:a}))};b.prototype.typeset=function(){var e,a,b,c;prettyPrint();c=this.$("#notebook");a=0;for(b=c.length;a<b;a++)e=c[a],console.log("tp",e),MathJax.Hub.Typeset(e);return this.$("#toc").html(this.generateToc())};
b.prototype.generateToc=function(){var e;e=$(document.createElement("div"));this.$(".cell").each(function(a,b){var c;c=$(document.createElement("div")).appendTo(e);c.addClass("toc-cell");c.attr("href",$(b).attr("id"));return $(b).find("h1, h2, h3").each(function(b,c){var d,s;s="title"+a+"_"+b;$(c).attr("id",s);d=$(document.createElement("div"));d.addClass(c.tagName);d.addClass("toc-entry");d.attr("href",s);d.html($(c).html());return e.append(d)})});return e};return b}(Backbone.View);p=function(c){function b(){this.renderCell=
d(this.renderCell,this);this.addAll=d(this.addAll,this);this.addOne=d(this.addOne,this);this.render=d(this.render,this);this.initialize=d(this.initialize,this);this.toggleEdit=d(this.toggleEdit,this);b.__super__.constructor.apply(this,arguments)}m(b,c);b.prototype.events={"click #toc":"handleTocJump","click #toggle-edit":"toggleEdit","click #save-to-file":"saveToFile","click #share-url":"share"};b.prototype.toggleEdit=function(){return a.router.navigate(this.model.get("id")+"/edit/",{trigger:!0})};
b.prototype.initialize=function(){this.template=_.template($("#notebook-template").html());this.cellTemplate=_.template($("#cell-view-template").html());$(".container").append(this.render());this.cells=this.$(".cells");console.log(this.cells);this.model.cells.fetch({success:this.addAll});if(a.mathjaxReady)return this.typeset()};b.prototype.render=function(){$(this.el).html(this.template());return this.el};b.prototype.addOne=function(a){return this.cells.append(this.renderCell(a))};b.prototype.addAll=
function(a){return a.each(this.addOne)};b.prototype.renderCell=function(a){a=a.toJSON();a.input=a.input.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");return this.cellTemplate(a)};return b}(f);l=function(c){function b(){this.toggleEdit=d(this.toggleEdit,this);this.spawnKeypress=d(this.spawnKeypress,this);this.spawnCellAtEnd=d(this.spawnCellAtEnd,this);this.addAll=d(this.addAll,this);this.addOne=d(this.addOne,this);this.render=d(this.render,this);this.initialize=d(this.initialize,
this);this.events=d(this.events,this);b.__super__.constructor.apply(this,arguments)}m(b,c);b.prototype.events=function(){return{"click #toc":"handleTocJump","dblclick #spawner":"spawnCellAtEnd","keyup #spawner":"spawnKeypress","click #toggle-edit":"toggleEdit","click #save-to-file":"saveToFile","click #share-url":"share"}};b.prototype.initialize=function(){this.template=_.template($("#notebook-template").html());$(".container").append(this.render());this.cells=this.$(".cells");this.model.cells.bind("add",
this.addOne);this.model.cells.bind("refresh",this.addAll);this.model.cells.fetch({success:this.addAll});if(a.mathjaxReady)return console.log("calling typeset at init"),this.typeset()};b.prototype.render=function(){$(this.el).html(this.template());return this.el};b.prototype.addOne=function(e){var b,c;a.c=e;c=new k({model:e});b=c.render();e=this.model.cells.indexOf(e);0===e?this.cells.prepend(b):(e=this.model.cells.at(e-1),e=e.view,$(e.el).after(b));c.afterDomInsert();return c.focusInput()};b.prototype.addAll=
function(a){return a.each(this.addOne)};b.prototype.spawnCellAtEnd=function(){return this.model.cells.createAtEnd()};b.prototype.spawnKeypress=function(a){if(13===a.keyCode)return this.model.cells.createAtEnd();if(38===a.keyCode)return a=this.model.cells.length,this.model.cells.at(a-1).view.output.focus()};b.prototype.toggleEdit=function(){return a.router.navigate(this.model.get("id")+"/view/",{trigger:!0})};return b}(f);k=function(c){function b(){this.resizeEditor=d(this.resizeEditor,this);this.inputChange=
d(this.inputChange,this);this.toggle=d(this.toggle,this);this.spawnAbove=d(this.spawnAbove,this);this.remove=d(this.remove,this);this.interrupt=d(this.interrupt,this);this.destroy=d(this.destroy,this);this.evaluate=d(this.evaluate,this);this.setEditorHighlightMode=d(this.setEditorHighlightMode,this);this.focusCellBelow=d(this.focusCellBelow,this);this.focusCellAbove=d(this.focusCellAbove,this);this.blurInput=d(this.blurInput,this);this.focusInput=d(this.focusInput,this);this.changeInputFold=d(this.changeInputFold,
this);this.toggleInputFold=d(this.toggleInputFold,this);this.handleKeypress=d(this.handleKeypress,this);this.afterDomInsert=d(this.afterDomInsert,this);this.changeState=d(this.changeState,this);this.changeOutput=d(this.changeOutput,this);this.changeType=d(this.changeType,this);this.render=d(this.render,this);this.logev=d(this.logev,this);this.initialize=d(this.initialize,this);this.events=d(this.events,this);b.__super__.constructor.apply(this,arguments)}m(b,c);b.prototype.tagName="li";b.prototype.events=
function(){return{"keyup .spawn-above":"handleKeypress","dblclick .spawn-above":"spawnAbove","click .evaluate":"evaluate","click .delete":"destroy","click .toggle":"toggle","click .type":"toggle","click .fold-button":"toggleInputFold","dblclick .cell-output":"toggleInputFold",evaluate:"evaluate",toggle:"toggle","click .interrupt":"interrupt","keyup .cell-output":"handleKeypress","focus .cell-input":"focusInput","blur .cell-input":"blurInput"}};b.prototype.initialize=function(){this.template=_.template($("#cell-edit-template").html());
this.model.bind("change:state",this.changeState);this.model.bind("change:type",this.changeType);this.model.bind("change:output",this.changeOutput);this.model.bind("change:inputFold",this.changeInputFold);this.model.bind("destroy",this.remove);this.model.view=this;return this.editor=null};b.prototype.logev=function(a){return console.log("in ev",a)};b.prototype.render=function(){var a;null==this.editor&&(a=this.model.toJSON(),null==this.model.id&&(a.id=this.model.cid),$(this.el).html(this.template(a)),
this.spawn=this.$(".spawn-above"),this.input=this.$(".cell-input"),this.output=this.$(".cell-output"),this.inputContainer=this.$(".ace-container"),this.type=this.$(".type"),this.intButton=this.$(".interrupt"),this.evalButton=this.$(".evaluate"));return this.el};b.prototype.changeType=function(){this.setEditorHighlightMode();return this.type.html(this.model.get("type"))};b.prototype.changeOutput=function(){this.output.html(this.model.get("output"));if(a.mathjaxReady)return MathJax.Hub.Typeset(this.output[0])};
b.prototype.changeState=function(){switch(this.model.get("state")){case "evaluating":return this.output.html("..."),this.intButton.addClass("active"),this.evalButton.removeClass("active");case "dirty":return this.evalButton.addClass("active");case null:return this.intButton.removeClass("active")}};b.prototype.afterDomInsert=function(){var a,b,c,d=this;this.editor=ace.edit("input-"+(null!=this.model.id?this.model.id:this.model.cid));this.model.set({state:null});this.editor.getSession().setUseWrapMode(!0);
this.editor.renderer.setShowGutter(!1);this.editor.renderer.setHScrollBarAlwaysVisible(!1);this.editor.renderer.setShowPrintMargin(!1);this.editor.setHighlightActiveLine(!1);this.$(".ace_sb").css({display:"none"});this.resizeEditor();this.editor.getSession().on("change",this.inputChange);this.setEditorHighlightMode();b=this.model.get("input");a=Math.max(3-_.string.count(b,"\n"),0);console.log("crs");c=_.range(a);a=0;for(c=c.length;a<c;a++)b+="\n";this.editor.getSession().setValue(b);this.model.get("inputFold")&&
this.changeInputFold();this.editor.commands.addCommand({name:"evaluate",bindKey:{win:"Ctrl-E",mac:"Command-E",sender:"editor"},exec:function(){return d.evaluate()}});this.editor.commands.addCommand({name:"toggleMode",bindKey:{win:"Ctrl-M",mac:"Command-M",sender:"editor"},exec:function(){return d.toggle()}});this.editor.commands.addCommand({name:"interrupt",bindKey:{win:"Ctrl-C",mac:"Ctrl-C",sender:"editor"},exec:function(){return d.interrupt()}});this.editor.commands.addCommand({name:"golineup",bindKey:{win:"Up",
mac:"Up|Ctrl-P",sender:"editor"},exec:function(a,b){var e;e=d.$(".ace_cursor");j(e)||r(e);return 0===a.getSession().getSelection().getCursor().row?(d.spawn.focus(),d.rogueKeyup=!0):a.navigateUp(b.times)}});this.editor.commands.addCommand({name:"golinedown",bindKey:{win:"Down",mac:"Down",sender:"editor"},exec:function(a,b){var e,c;e=d.$(".ace_cursor");j(e)||n(e);c=a.getSession().getSelection().getCursor().row;e=d.editor.getSession().getDocument().getLength()-1;return c===e?(d.output.focus(),d.rogueKeyup=
!0):a.navigateDown(b.times)}});return this.editor.commands.addCommand({name:"backspace",bindKey:{win:"Backspace",mac:"Backspace",sender:"editor"},exec:function(a){a=a.getSession();return 1===a.getLength()&&""===a.getValue()?d.destroy():d.editor.remove("left")}})};b.prototype.handleKeypress=function(a){var b,c;if(!0===this.rogueKeyup)this.rogueKeyup=!1;else if(b=this.model.get("inputFold"),c=a.target.className,38===a.keyCode)switch(c){case "cell-output":return b?this.spawn.focus():this.focusInput("bottom");
case "spawn-above":return this.focusCellAbove()}else if(40===a.keyCode)switch(c){case "cell-output":return this.focusCellBelow();case "spawn-above":return b?this.output.focus():this.focusInput("top")}else if(13===a.keyCode)switch(c){case "spawn-above":return this.spawnAbove();case "cell-output":return this.toggleInputFold()}};b.prototype.toggleInputFold=function(){return this.model.toggleInputFold()};b.prototype.changeInputFold=function(){this.inputContainer.toggleClass("input-fold");this.$(".fold-button").toggleClass("input-fold");
return this.$("hr").toggleClass("input-fold")};b.prototype.focusInput=function(a){"top"===a?(this.editor.gotoLine(1),this.editor.focus()):"bottom"===a&&(this.editor.gotoLine(this.editor.getSession().getDocument().getLength()),this.editor.focus());if(null!=this.editor)return this.editor.setHighlightActiveLine(!0),this.$(".ace_cursor-layer").show()};b.prototype.blurInput=function(){if(null!=this.editor)return this.editor.setHighlightActiveLine(!1),this.$(".ace_cursor-layer").hide()};b.prototype.focusCellAbove=
function(){var a;a=this.model.collection.at(this.model.collection.indexOf(this.model)-1);if(null!=a)return a.view.output.focus()};b.prototype.focusCellBelow=function(){var a;a=this.model.collection.at(this.model.collection.indexOf(this.model)+1);return null!=a?a.view.spawn.focus():$("#spawner").focus()};b.prototype.setEditorHighlightMode=function(){var a;"javascript"===this.model.get("type")?a=require("ace/mode/javascript").Mode:"markdown"===this.model.get("type")&&(a=require("ace/mode/markdown").Mode);
if(null!=a)return this.editor.getSession().setMode(new a)};b.prototype.evaluate=function(){this.model.set({input:this.editor.getSession().getValue()});return this.model.evaluate()};b.prototype.destroy=function(){return this.model.destroy()};b.prototype.interrupt=function(){return this.model.interrupt()};b.prototype.remove=function(){return $(this.el).fadeOut("fast",$(this.el).remove)};b.prototype.spawnAbove=function(){return this.model.collection.createBefore(this.model)};b.prototype.toggle=function(){return this.model.toggleType()};
b.prototype.inputChange=function(){this.model.set({state:"dirty"});return this.resizeEditor()};b.prototype.resizeEditor=function(){var a,b;a=this.editor.renderer.$textLayer.getLineHeight();b=this.editor.getSession().getScreenLength();if(1===a)setTimeout(this.resizeEditor,200);else return this.$(".ace-container").height(20+a*b),this.editor.resize()};return b}(Backbone.View);g=function(c){function b(){this.mathjaxReady=d(this.mathjaxReady,this);this.loadFile=d(this.loadFile,this);this["new"]=d(this["new"],
this);this.addNbs=d(this.addNbs,this);this.addNb=d(this.addNb,this);this.render=d(this.render,this);this.initialize=d(this.initialize,this);b.__super__.constructor.apply(this,arguments)}m(b,c);b.prototype.className="app";b.prototype.events={"click #new-notebook-button":"new","change #load-file":"loadFile"};b.prototype.initialize=function(){this.template=_.template($("#index-template").html());$(".container").append(this.render());return this.addNbs()};b.prototype.render=function(){$(this.el).html(this.template());
return this.el};b.prototype.addNb=function(a){return $("#notebooks").append(this.nbtemplate(a.toJSON()))};b.prototype.addNbs=function(){this.nbtemplate=_.template($("#notebook-index-template").html());return a.notebooks.each(this.addNb)};b.prototype["new"]=function(){console.log("new");return a.router.navigate("new/",{trigger:!0})};b.prototype.loadFile=function(b){var c,b=b.target.files[0];c=new FileReader;c.onload=function(b){b=JSON.parse(b.target.result);b=o(b);return a.router.navigate(b.get("id")+
"/view/",{trigger:!0})};return c.readAsText(b)};b.prototype.mathjaxReady=function(){};return b}(Backbone.View);i=function(c){function b(){this.mathjaxReady=d(this.mathjaxReady,this);this.create=d(this.create,this);this.render=d(this.render,this);this.initialize=d(this.initialize,this);b.__super__.constructor.apply(this,arguments)}m(b,c);b.prototype.className="app";b.prototype.events={"click button":"create"};b.prototype.initialize=function(){this.template=_.template($("#new-notebook-form").html());
return $(".container").append(this.render())};b.prototype.render=function(){$(this.el).html(this.template());return this.el};b.prototype.create=function(){var b;b=a.notebooks.create({title:this.$("input").val()},{wait:!0});b.readyCells();b.cells.create({position:b.cells.posJump});return a.router.navigate(b.id+"/edit/",{trigger:!0})};b.prototype.mathjaxReady=function(){};return b}(Backbone.View);h=function(c){function b(){this["import"]=d(this["import"],this);this.loadUrl=d(this.loadUrl,this);this.index=
d(this.index,this);this["new"]=d(this["new"],this);this["delete"]=d(this["delete"],this);this.view=d(this.view,this);this.edit=d(this.edit,this);this.getNotebook=d(this.getNotebook,this);this.unmatched=d(this.unmatched,this);b.__super__.constructor.apply(this,arguments)}m(b,c);b.prototype.routes={":nb/edit/":"edit",":nb/view/":"view",":nb/delete/":"delete","load/*url":"loadUrl","new/":"new","import/*data/":"import","":"index"};b.prototype.unmatched=function(a){return console.log(a)};b.prototype.getNotebook=
function(b){b=a.notebooks.get(b);b.readyCells();a.nb=b;console.log("notebook loaded; id="+b.get("id"));return b};b.prototype.edit=function(b){a.app&&a.app.remove();console.log("activated edit route",b);b=this.getNotebook(b);a.app=new l({model:b});return q(b.get("title")+" (Editing)")};b.prototype.view=function(b){a.app&&a.app.remove();console.log("activated view route");b=this.getNotebook(b);q(b.get("title")+" (Viewing)");return a.app=new p({model:b})};b.prototype["delete"]=function(b){console.log("deleting nb",
b);confirm("You really want to delete that?")&&(b=this.getNotebook(b),b.cells.fetch({success:function(a){return a.each(function(a){console.log("destroy",a);return a.destroy()})}}),console.log("cells",b.cells.length),b.destroy(),console.log("deleted"));return a.router.navigate("",{trigger:!0})};b.prototype["new"]=function(){console.log("new view");a.app&&a.app.remove();return a.app=new i};b.prototype.index=function(){a.app&&(a.app.remove(),a.nb=null);console.log("index view");q("");return a.app=new g};
b.prototype.loadUrl=function(b){console.log("loading url");return $.getJSON(b,function(b){b=o(b);return a.router.navigate(b.get("id")+"/view/",{trigger:!0})})};b.prototype["import"]=function(b){b=JSON.parse(atob(b));b=o(b);return a.router.navigate(b.get("id")+"/view/",{trigger:!0})};return b}(Backbone.Router);q=function(a){return $("#title").html(a)};o=function(c){var b,d,f,h,g,i;d=c.cells;delete c.cells;c.title=c.title;try{a.notebooks.get(c.id)&&raise("duplicate");console.log("no such nb",c.id);
console.log("import notebook");f=a.notebooks.create(c);f.readyCells();h=function(a){return f.cells.create(a)};g=0;for(i=d.length;g<i;g++)b=d[g],h(b);return f}catch(j){return alert("Could not import notebook probably because it already exists.  try deleting"),console.log(j)}};c=function(){a.mathjaxReady=!0;return a.app.mathjaxReady()};$(document).ready(function(){console.log("creating app");a.notebooks=new a.Notebooks;a.notebooks.fetch();a.mathjaxReady=!1;a.router=new h;Backbone.history.start();return MathJax.Hub.Register.StartupHook("End",
c)})}).call(this);
