(function(){var f,k,l,h,i,b,g=function(b,c){return function(){return b.apply(c,arguments)}},p=Object.prototype.hasOwnProperty,j=function(b,c){function n(){this.constructor=b}for(var g in c)p.call(c,g)&&(b[g]=c[g]);n.prototype=c.prototype;b.prototype=new n;b.__super__=c.prototype;return b};i="undefined"!==typeof exports&&null!==exports?exports:this;h=i.NotebookJS=null!=(b=i.NotebookJS)?b:{};l=function(b){function c(){this.serialize=g(this.serialize,this);this.readyCells=g(this.readyCells,this);this.initialize=
g(this.initialize,this);this.defaults=g(this.defaults,this);c.__super__.constructor.apply(this,arguments)}j(c,b);c.prototype.defaults=function(){return{title:"untitled"}};c.prototype.initialize=function(){};c.prototype.readyCells=function(){this.cells=new k;return this.cells.localStorage=new Store("cells-"+this.get("id"))};c.prototype.serialize=function(){var b;b=this.toJSON();b.cells=this.cells.toJSON();return JSON.stringify(b)};return c}(Backbone.Model);i=function(b){function c(){c.__super__.constructor.apply(this,
arguments)}j(c,b);c.prototype.model=l;c.prototype.localStorage=new Store("notebook.js");return c}(Backbone.Collection);f=function(b){function c(){this.handleMessage=g(this.handleMessage,this);this.evaluateError=g(this.evaluateError,this);this.evaluateSuccess=g(this.evaluateSuccess,this);this.interrupt=g(this.interrupt,this);this.evaluate=g(this.evaluate,this);this.toggleInputFold=g(this.toggleInputFold,this);this.toggleType=g(this.toggleType,this);this.defaults=g(this.defaults,this);c.__super__.constructor.apply(this,
arguments)}j(c,b);c.prototype.tagName="li";c.prototype.defaults=function(){return{input:"",type:"javascript",inputFold:!1,output:null,position:null,error:null,state:null}};c.prototype.toggleType=function(){"javascript"===this.get("type")?this.set({type:"markdown"}):this.set({type:"javascript"});return this.set({state:"dirty"})};c.prototype.toggleInputFold=function(){this.set({inputFold:!this.get("inputFold")});return this.save()};c.prototype.evaluate=function(){this.set({output:null,error:null});
this.set({state:"evaluating"});this.save();this.handler=h.engines[this.get("type")];return this.handler.evaluate(this.get("input"),this)};c.prototype.interrupt=function(){if(null!=this.handler)return this.onPrint("Interrupted","error"),this.handler.interrupt(),this.set({state:null}),this.save()};c.prototype.evaluateSuccess=function(b){this.set({output:b,error:null});return this.save()};c.prototype.evaluateError=function(b){this.set({error:b});return this.save};c.prototype.handleMessage=function(b){switch(b.msg){case "evalEnd":return this.set({state:null}),
this.save();case "error":return this.onPrint(b.data,"error");case "print":return this.onPrint(b.data,"print");case "result":return this.onPrint(b.data,"print");case "raw":return this.onPrint(b.data,"raw")}};c.prototype.onError=function(b){return this.set({error:b})};c.prototype.onPrint=function(b,c){return this.set({output:(this.get("output")||"").concat('<div class="'+c+'">'+b+"</div>")})};return c}(Backbone.Model);k=function(b){function c(){this.comparator=g(this.comparator,this);c.__super__.constructor.apply(this,
arguments)}j(c,b);c.prototype.model=f;c.prototype.posJump=Math.pow(2,16);c.prototype.comparator=function(b,c){b=b.get("position");c=c.get("position");return b>c?1:b<c?-1:0};c.prototype.createAtEnd=function(){return this.create({position:this.length?this.at(this.length-1).get("position")+this.posJump:this.posJump})};c.prototype.createBefore=function(b){var c;c=this.indexOf(b);b=b.get("position");c=0===c?0:this.at(c-1).get("position");return this.create({position:(b+c)/2})};return c}(Backbone.Collection);
h.Notebook=l;h.Notebooks=i;h.Cell=f;h.Cells=k}).call(this);(function(){var f,k,l,h,i=function(b,g){return function(){return b.apply(g,arguments)}};k="undefined"!==typeof exports&&null!==exports?exports:this;k=k.NotebookJS=null!=(f=k.NotebookJS)?f:{};(function(){function b(){this.evaluate=i(this.evaluate,this)}b.prototype.evaluate=function(b,f){var j;try{if(j=eval(b),null!=j)return console.log("result",j),f.handleMessage({msg:"result",data:j.toString()})}catch(h){return console.log(h.message,h.stack),f.handleMessage({msg:"error",data:h.toString()})}finally{f.handleMessage({msg:"evalEnd"})}};
return b})();f=function(){function b(){this.evaluate=i(this.evaluate,this)}b.prototype.evaluate=function(b,f){var h,i;try{return i=new Showdown.converter,h=i.makeHtml(b),f.handleMessage({msg:"raw",data:h})}catch(c){return console.log(c.message),onErr(c.message)}finally{f.handleMessage({msg:"evalEnd"})}};return b}();l=function(){function b(){this.interrupt=i(this.interrupt,this);this.handleMessage=i(this.handleMessage,this);this.evaluate=i(this.evaluate,this);this.worker=new Worker("/src/worker.js");
this.worker.onmessage=this.handleMessage;this.inputId=0;this.handlers={}}b.prototype.evaluate=function(b,f){this.inputId+=1;this.handlers[this.inputId]=f;return this.worker.postMessage({src:b,id:this.inputId})};b.prototype.handleMessage=function(b){return this.handlers[b.data.inputId].handleMessage(b.data)};b.prototype.interrupt=function(){this.worker.terminate();this.worker=new Worker("/src/worker.js");return this.worker.onmessage=this.handleMessage};return b}();h={};h.javascript=new l;h.markdown=
new f;k.engines=h}).call(this);(function(){var f,k,l,h,i,b,g,p,j,o,c,n,r,q,t,d=function(b,a){return function(){return b.apply(a,arguments)}},u=Object.prototype.hasOwnProperty,m=function(b,a){function e(){this.constructor=b}for(var c in a)u.call(a,c)&&(b[c]=a[c]);e.prototype=a.prototype;b.prototype=new e;b.__super__=a.prototype;return b};_.templateSettings={interpolate:/\[\[=(.+?)\]\]/g,evaluate:/\[\[(.+?)\]\]/g};f="undefined"!==typeof exports&&null!==exports?exports:this;b=f.NotebookJS=null!=(t=f.NotebookJS)?t:{};j=function(b){var a,
e,c;e=$(window).scrollTop()+60;a=$(window).scrollTop()+$(window).height()-30;c=b.offset().top;return c+b.height()<=a&&c>=e};r=function(b){b=b.offset().top-90;console.log("stat",b);return $(window).scrollTop(b)};n=function(b){b=b.offset().top+b.height()+60-$(window).height();console.log("stab",b);return $("body").scrollTop(b)};f=function(c){function a(){this.generateToc=d(this.generateToc,this);this.typeset=d(this.typeset,this);this.share=d(this.share,this);this.saveToFile=d(this.saveToFile,this);
this.mathjaxReady=d(this.mathjaxReady,this);this.handleTocJump=d(this.handleTocJump,this);a.__super__.constructor.apply(this,arguments)}m(a,c);a.prototype.className="app";a.prototype.handleTocJump=function(e){window.e=e;if(e=$(e.target).attr("href"))return e=$("#"+e),r(e)};a.prototype.mathjaxReady=function(){return this.typeset()};a.prototype.saveToFile=function(e){var b;b=this.model.serialize();$(e.target).attr("download","notebook-"+(new Date).toISOString().slice(0,10)+".json");return $(e.target).attr("href",
"data:application/json;charset=utf-8,"+escape(b))};a.prototype.share=function(){var e,a;e=b.util.base64UrlEncode(this.model.serialize());a="http://"+location.host+"/#import/"+escape(e)+"/";e=_.template($("#share-notebook").html());return(new b.util.ModalDialog(e({url:a}))).element.find("input").focus().select()};a.prototype.typeset=function(){var e,b,a,c;prettyPrint();c=this.$("#notebook");b=0;for(a=c.length;b<a;b++)e=c[b],console.log("tp",e),MathJax.Hub.Typeset(e);return this.$("#toc").html(this.generateToc())};
a.prototype.generateToc=function(){var e;e=$(document.createElement("div"));this.$(".cell").each(function(b,a){var c;c=$(document.createElement("div")).appendTo(e);c.addClass("toc-cell");c.attr("href",$(a).attr("id"));return $(a).find("h1, h2, h3").each(function(a,c){var d,s;s="title"+b+"_"+a;$(c).attr("id",s);d=$(document.createElement("div"));d.addClass(c.tagName);d.addClass("toc-entry");d.attr("href",s);d.html($(c).html());return e.append(d)})});return e};return a}(Backbone.View);p=function(c){function a(){this.renderCell=
d(this.renderCell,this);this.addAll=d(this.addAll,this);this.addOne=d(this.addOne,this);this.render=d(this.render,this);this.initialize=d(this.initialize,this);this.toggleEdit=d(this.toggleEdit,this);a.__super__.constructor.apply(this,arguments)}m(a,c);a.prototype.events={"click #toc":"handleTocJump","click #toggle-edit":"toggleEdit","click #save-to-file":"saveToFile","click #share-url":"share","dblclick #notebook":"toggleEdit"};a.prototype.toggleEdit=function(){return b.router.navigate(this.model.get("id")+
"/edit/",{trigger:!0})};a.prototype.initialize=function(){this.template=_.template($("#notebook-template").html());this.cellTemplate=_.template($("#cell-view-template").html());$(".container").append(this.render());this.cells=this.$(".cells");console.log(this.cells);this.model.cells.fetch({success:this.addAll});if(b.mathjaxReady)return this.typeset()};a.prototype.render=function(){$(this.el).html(this.template());return this.el};a.prototype.addOne=function(e){return this.cells.append(this.renderCell(e))};
a.prototype.addAll=function(e){return e.each(this.addOne)};a.prototype.renderCell=function(e){e=e.toJSON();e.input=e.input.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");return this.cellTemplate(e)};return a}(f);l=function(c){function a(){this.toggleEdit=d(this.toggleEdit,this);this.spawnKeypress=d(this.spawnKeypress,this);this.spawnCellAtEnd=d(this.spawnCellAtEnd,this);this.addAll=d(this.addAll,this);this.addOne=d(this.addOne,this);this.render=d(this.render,this);this.initialize=
d(this.initialize,this);this.events=d(this.events,this);a.__super__.constructor.apply(this,arguments)}m(a,c);a.prototype.events=function(){return{"click #toc":"handleTocJump","dblclick #spawner":"spawnCellAtEnd","keyup #spawner":"spawnKeypress","click #toggle-edit":"toggleEdit","click #save-to-file":"saveToFile","click #share-url":"share"}};a.prototype.initialize=function(){this.template=_.template($("#notebook-template").html());$(".container").append(this.render());this.cells=this.$(".cells");this.model.cells.bind("add",
this.addOne);this.model.cells.bind("refresh",this.addAll);this.model.cells.fetch({success:this.addAll});if(b.mathjaxReady)return console.log("calling typeset at init"),this.typeset()};a.prototype.render=function(){$(this.el).html(this.template());return this.el};a.prototype.addOne=function(e){var a,c;b.c=e;c=new k({model:e});a=c.render();e=this.model.cells.indexOf(e);0===e?this.cells.prepend(a):(e=this.model.cells.at(e-1),e=e.view,$(e.el).after(a));c.afterDomInsert();return c.focusInput()};a.prototype.addAll=
function(e){return e.each(this.addOne)};a.prototype.spawnCellAtEnd=function(){return this.model.cells.createAtEnd()};a.prototype.spawnKeypress=function(e){if(13===e.keyCode)return this.model.cells.createAtEnd();if(38===e.keyCode)return e=this.model.cells.length,this.model.cells.at(e-1).view.output.focus()};a.prototype.toggleEdit=function(){return b.router.navigate(this.model.get("id")+"/view/",{trigger:!0})};return a}(f);k=function(c){function a(){this.resizeEditor=d(this.resizeEditor,this);this.inputChange=
d(this.inputChange,this);this.toggle=d(this.toggle,this);this.spawnAbove=d(this.spawnAbove,this);this.remove=d(this.remove,this);this.interrupt=d(this.interrupt,this);this.destroy=d(this.destroy,this);this.evaluate=d(this.evaluate,this);this.setEditorHighlightMode=d(this.setEditorHighlightMode,this);this.focusCellBelow=d(this.focusCellBelow,this);this.focusCellAbove=d(this.focusCellAbove,this);this.blurInput=d(this.blurInput,this);this.focusInput=d(this.focusInput,this);this.changeInputFold=d(this.changeInputFold,
this);this.toggleInputFold=d(this.toggleInputFold,this);this.handleKeypress=d(this.handleKeypress,this);this.afterDomInsert=d(this.afterDomInsert,this);this.changeState=d(this.changeState,this);this.changeOutput=d(this.changeOutput,this);this.changeType=d(this.changeType,this);this.render=d(this.render,this);this.logev=d(this.logev,this);this.initialize=d(this.initialize,this);this.events=d(this.events,this);a.__super__.constructor.apply(this,arguments)}m(a,c);a.prototype.tagName="li";a.prototype.events=
function(){return{"keyup .spawn-above":"handleKeypress","dblclick .spawn-above":"spawnAbove","click .evaluate":"evaluate","click .delete":"destroy","click .toggle":"toggle","click .type":"toggle","click .fold-button":"toggleInputFold","dblclick .cell-output":"toggleInputFold",evaluate:"evaluate",toggle:"toggle","click .interrupt":"interrupt","keyup .cell-output":"handleKeypress","focus .cell-input":"focusInput","blur .cell-input":"blurInput"}};a.prototype.initialize=function(){this.template=_.template($("#cell-edit-template").html());
this.model.bind("change:state",this.changeState);this.model.bind("change:type",this.changeType);this.model.bind("change:output",this.changeOutput);this.model.bind("change:inputFold",this.changeInputFold);this.model.bind("destroy",this.remove);this.model.view=this;return this.editor=null};a.prototype.logev=function(e){return console.log("in ev",e)};a.prototype.render=function(){var e;null==this.editor&&(e=this.model.toJSON(),null==this.model.id&&(e.id=this.model.cid),$(this.el).html(this.template(e)),
this.spawn=this.$(".spawn-above"),this.input=this.$(".cell-input"),this.output=this.$(".cell-output"),this.inputContainer=this.$(".ace-container"),this.type=this.$(".type"),this.intButton=this.$(".interrupt"),this.evalButton=this.$(".evaluate"));return this.el};a.prototype.changeType=function(){this.setEditorHighlightMode();return this.type.html(this.model.get("type"))};a.prototype.changeOutput=function(){this.output.html(this.model.get("output"));if(b.mathjaxReady)return MathJax.Hub.Typeset(this.output[0])};
a.prototype.changeState=function(){switch(this.model.get("state")){case "evaluating":return this.output.html("..."),this.intButton.addClass("active"),this.evalButton.removeClass("active");case "dirty":return this.evalButton.addClass("active");case null:return this.intButton.removeClass("active")}};a.prototype.afterDomInsert=function(){var e,b,a,c=this;this.editor=ace.edit("input-"+(null!=this.model.id?this.model.id:this.model.cid));this.model.set({state:null});this.editor.getSession().setUseWrapMode(!0);
this.editor.renderer.setShowGutter(!1);this.editor.renderer.setHScrollBarAlwaysVisible(!1);this.editor.renderer.setShowPrintMargin(!1);this.editor.setHighlightActiveLine(!1);this.$(".ace_sb").css({display:"none"});b=this.model.get("input");e=Math.max(3-_.string.count(b,"\n"),0);console.log("crs");a=_.range(e);e=0;for(a=a.length;e<a;e++)b+="\n";this.editor.getSession().setValue(b);this.resizeEditor();this.editor.getSession().on("change",this.inputChange);this.setEditorHighlightMode();this.model.get("inputFold")&&
this.changeInputFold();this.editor.commands.addCommand({name:"evaluate",bindKey:{win:"Ctrl-E",mac:"Command-E",sender:"editor"},exec:function(){return c.evaluate()}});this.editor.commands.addCommand({name:"toggleMode",bindKey:{win:"Ctrl-M",mac:"Command-M",sender:"editor"},exec:function(){return c.toggle()}});this.editor.commands.addCommand({name:"interrupt",bindKey:{win:"Ctrl-C",mac:"Ctrl-C",sender:"editor"},exec:function(){return c.interrupt()}});this.editor.commands.addCommand({name:"golineup",bindKey:{win:"Up",
mac:"Up|Ctrl-P",sender:"editor"},exec:function(b,e){var a;a=c.$(".ace_cursor");j(a)||r(a);return 0===b.getSession().getSelection().getCursor().row?(c.spawn.focus(),c.rogueKeyup=!0):b.navigateUp(e.times)}});this.editor.commands.addCommand({name:"golinedown",bindKey:{win:"Down",mac:"Down",sender:"editor"},exec:function(b,e){var a,d;a=c.$(".ace_cursor");j(a)||n(a);d=b.getSession().getSelection().getCursor().row;a=c.editor.getSession().getDocument().getLength()-1;return d===a?(c.output.focus(),c.rogueKeyup=
!0):b.navigateDown(e.times)}});return this.editor.commands.addCommand({name:"backspace",bindKey:{win:"Backspace",mac:"Backspace",sender:"editor"},exec:function(b){b=b.getSession();return 1===b.getLength()&&""===b.getValue()?c.destroy():c.editor.remove("left")}})};a.prototype.handleKeypress=function(b){var a,c;if(!0===this.rogueKeyup)this.rogueKeyup=!1;else if(a=this.model.get("inputFold"),c=b.target.className,38===b.keyCode)switch(c){case "cell-output":return a?this.spawn.focus():this.focusInput("bottom");
case "spawn-above":return this.focusCellAbove()}else if(40===b.keyCode)switch(c){case "cell-output":return this.focusCellBelow();case "spawn-above":return a?this.output.focus():this.focusInput("top")}else if(13===b.keyCode)switch(c){case "spawn-above":return this.spawnAbove();case "cell-output":return this.toggleInputFold()}};a.prototype.toggleInputFold=function(){return this.model.toggleInputFold()};a.prototype.changeInputFold=function(){this.inputContainer.toggleClass("input-fold");this.$(".fold-button").toggleClass("input-fold");
return this.$("hr").toggleClass("input-fold")};a.prototype.focusInput=function(b){"top"===b?(this.editor.gotoLine(1),this.editor.focus()):"bottom"===b&&(this.editor.gotoLine(this.editor.getSession().getDocument().getLength()),this.editor.focus());if(null!=this.editor)return this.editor.setHighlightActiveLine(!0),this.$(".ace_cursor-layer").show()};a.prototype.blurInput=function(){if(null!=this.editor)return this.editor.setHighlightActiveLine(!1),this.$(".ace_cursor-layer").hide()};a.prototype.focusCellAbove=
function(){var b;b=this.model.collection.at(this.model.collection.indexOf(this.model)-1);if(null!=b)return b.view.output.focus()};a.prototype.focusCellBelow=function(){var b;b=this.model.collection.at(this.model.collection.indexOf(this.model)+1);return null!=b?b.view.spawn.focus():$("#spawner").focus()};a.prototype.setEditorHighlightMode=function(){var b;"javascript"===this.model.get("type")?b=require("ace/mode/javascript").Mode:"markdown"===this.model.get("type")&&(b=require("ace/mode/markdown").Mode);
if(null!=b)return this.editor.getSession().setMode(new b)};a.prototype.evaluate=function(){this.model.set({input:this.editor.getSession().getValue()});return this.model.evaluate()};a.prototype.destroy=function(){return this.model.destroy()};a.prototype.interrupt=function(){return this.model.interrupt()};a.prototype.remove=function(){return $(this.el).fadeOut("fast",$(this.el).remove)};a.prototype.spawnAbove=function(){return this.model.collection.createBefore(this.model)};a.prototype.toggle=function(){return this.model.toggleType()};
a.prototype.inputChange=function(){this.model.set({state:"dirty"});return this.resizeEditor()};a.prototype.resizeEditor=function(){var b,a;b=this.editor.renderer.$textLayer.getLineHeight();a=this.editor.getSession().getScreenLength();if(1===b)setTimeout(this.resizeEditor,200);else return this.$(".ace-container").height(20+b*a),this.editor.resize()};return a}(Backbone.View);h=function(c){function a(){this.mathjaxReady=d(this.mathjaxReady,this);this.loadFile=d(this.loadFile,this);this["new"]=d(this["new"],
this);this.addNbs=d(this.addNbs,this);this.addNb=d(this.addNb,this);this.render=d(this.render,this);this.initialize=d(this.initialize,this);a.__super__.constructor.apply(this,arguments)}m(a,c);a.prototype.className="app";a.prototype.events={"click #new-notebook-button":"new","change #load-file":"loadFile"};a.prototype.initialize=function(){this.template=_.template($("#index-template").html());$(".container").append(this.render());return this.addNbs()};a.prototype.render=function(){$(this.el).html(this.template());
return this.el};a.prototype.addNb=function(b){return $("#notebooks").append(this.nbtemplate(b.toJSON()))};a.prototype.addNbs=function(){this.nbtemplate=_.template($("#notebook-index-template").html());return b.notebooks.each(this.addNb)};a.prototype["new"]=function(){console.log("new");return b.router.navigate("new/",{trigger:!0})};a.prototype.loadFile=function(a){var c,a=a.target.files[0];c=new FileReader;c.onload=function(a){a=JSON.parse(a.target.result);a=o(a);return b.router.navigate(a.get("id")+
"/view/",{trigger:!0})};return c.readAsText(a)};a.prototype.mathjaxReady=function(){};return a}(Backbone.View);i=function(c){function a(){this.mathjaxReady=d(this.mathjaxReady,this);this.create=d(this.create,this);this.render=d(this.render,this);this.initialize=d(this.initialize,this);a.__super__.constructor.apply(this,arguments)}m(a,c);a.prototype.className="app";a.prototype.events={"click button":"create"};a.prototype.initialize=function(){this.template=_.template($("#new-notebook-form").html());
return $(".container").append(this.render())};a.prototype.render=function(){$(this.el).html(this.template());return this.el};a.prototype.create=function(){var a;a=b.notebooks.create({title:this.$("input").val()},{wait:!0});a.readyCells();a.cells.create({position:a.cells.posJump});return b.router.navigate(a.id+"/edit/",{trigger:!0})};a.prototype.mathjaxReady=function(){};return a}(Backbone.View);g=function(c){function a(){this["import"]=d(this["import"],this);this.loadUrl=d(this.loadUrl,this);this.index=
d(this.index,this);this["new"]=d(this["new"],this);this["delete"]=d(this["delete"],this);this.view=d(this.view,this);this.edit=d(this.edit,this);this.getNotebook=d(this.getNotebook,this);this.unmatched=d(this.unmatched,this);a.__super__.constructor.apply(this,arguments)}m(a,c);a.prototype.routes={":nb/edit/":"edit",":nb/view/":"view",":nb/delete/":"delete","load/*url":"loadUrl","new/":"new","import/*data/":"import","":"index"};a.prototype.unmatched=function(b){return console.log(b)};a.prototype.getNotebook=
function(a){a=b.notebooks.get(a);a.readyCells();b.nb=a;console.log("notebook loaded; id="+a.get("id"));return a};a.prototype.edit=function(a){b.app&&b.app.remove();console.log("activated edit route",a);a=this.getNotebook(a);b.app=new l({model:a});return q(a.get("title")+" (Editing)")};a.prototype.view=function(a){b.app&&b.app.remove();console.log("activated view route");a=this.getNotebook(a);q(a.get("title")+" (Viewing)");return b.app=new p({model:a})};a.prototype["delete"]=function(a){console.log("deleting nb",
a);confirm("You really want to delete that?")&&(a=this.getNotebook(a),a.cells.fetch({success:function(a){return a.each(function(a){console.log("destroy",a);return a.destroy()})}}),console.log("cells",a.cells.length),a.destroy(),console.log("deleted"));return b.router.navigate("",{trigger:!0})};a.prototype["new"]=function(){console.log("new view");b.app&&b.app.remove();return b.app=new i};a.prototype.index=function(){b.app&&(b.app.remove(),b.nb=null);console.log("index view");q("");return b.app=new h};
a.prototype.loadUrl=function(a){console.log("loading url");return $.getJSON(a,function(a){a=o(a);return b.router.navigate(a.get("id")+"/view/",{trigger:!0,replace:!0})})};a.prototype["import"]=function(a){a=JSON.parse(b.util.base64UrlDecode(a));a=o(a);return b.router.navigate(a.get("id")+"/view/",{trigger:!0,replace:!0})};return a}(Backbone.Router);q=function(b){return $("#title").html(b)};o=function(c){var a,e,d,f,g,h;e=c.cells;delete c.cells;c.title=c.title;try{b.notebooks.get(c.id)&&raise("duplicate");
console.log("no such nb",c.id);console.log("import notebook");d=b.notebooks.create(c);d.readyCells();f=function(a){return d.cells.create(a)};g=0;for(h=e.length;g<h;g++)a=e[g],f(a);return d}catch(i){return alert("Could not import notebook probably because it already exists.  try deleting"),console.log(i)}};c=function(){b.mathjaxReady=!0;return b.app.mathjaxReady()};$(document).ready(function(){console.log("creating app");b.notebooks=new b.Notebooks;b.notebooks.fetch();b.mathjaxReady=!1;b.router=new g;
Backbone.history.start();return MathJax.Hub.Register.StartupHook("End",c)})}).call(this);
